//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCExtractorGUI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InputType {
            get {
                return ((string)(this["InputType"]));
            }
            set {
                this["InputType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SplitType {
            get {
                return ((string)(this["SplitType"]));
            }
            set {
                this["SplitType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Field1 {
            get {
                return ((bool)(this["Field1"]));
            }
            set {
                this["Field1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Field2 {
            get {
                return ((bool)(this["Field2"]));
            }
            set {
                this["Field2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Channel2 {
            get {
                return ((bool)(this["Channel2"]));
            }
            set {
                this["Channel2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ModeLive {
            get {
                return ((bool)(this["ModeLive"]));
            }
            set {
                this["ModeLive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal LiveTimeOut {
            get {
                return ((decimal)(this["LiveTimeOut"]));
            }
            set {
                this["LiveTimeOut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProcessFromStart {
            get {
                return ((bool)(this["ProcessFromStart"]));
            }
            set {
                this["ProcessFromStart"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ProcessToEnd {
            get {
                return ((bool)(this["ProcessToEnd"]));
            }
            set {
                this["ProcessToEnd"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ProcessFromHH {
            get {
                return ((decimal)(this["ProcessFromHH"]));
            }
            set {
                this["ProcessFromHH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ProcessFromMM {
            get {
                return ((decimal)(this["ProcessFromMM"]));
            }
            set {
                this["ProcessFromMM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ProcessFromSS {
            get {
                return ((decimal)(this["ProcessFromSS"]));
            }
            set {
                this["ProcessFromSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ProcessToHH {
            get {
                return ((decimal)(this["ProcessToHH"]));
            }
            set {
                this["ProcessToHH"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ProcessToMM {
            get {
                return ((decimal)(this["ProcessToMM"]));
            }
            set {
                this["ProcessToMM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ProcessToSS {
            get {
                return ((decimal)(this["ProcessToSS"]));
            }
            set {
                this["ProcessToSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProcessToScreenfulLimit {
            get {
                return ((bool)(this["ProcessToScreenfulLimit"]));
            }
            set {
                this["ProcessToScreenfulLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal ScreenfulLimit {
            get {
                return ((decimal)(this["ScreenfulLimit"]));
            }
            set {
                this["ScreenfulLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UseMythTVbranch {
            get {
                return ((string)(this["UseMythTVbranch"]));
            }
            set {
                this["UseMythTVbranch"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Clock90090 {
            get {
                return ((bool)(this["Clock90090"]));
            }
            set {
                this["Clock90090"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FixPadding {
            get {
                return ((bool)(this["FixPadding"]));
            }
            set {
                this["FixPadding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LargeGOPs {
            get {
                return ((bool)(this["LargeGOPs"]));
            }
            set {
                this["LargeGOPs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputType {
            get {
                return ((string)(this["OutputType"]));
            }
            set {
                this["OutputType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal TimeAdjust {
            get {
                return ((decimal)(this["TimeAdjust"]));
            }
            set {
                this["TimeAdjust"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugInterestingPackets {
            get {
                return ((bool)(this["DebugInterestingPackets"]));
            }
            set {
                this["DebugInterestingPackets"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug608 {
            get {
                return ((bool)(this["Debug608"]));
            }
            set {
                this["Debug608"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Debug708 {
            get {
                return ((bool)(this["Debug708"]));
            }
            set {
                this["Debug708"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugTimestamp {
            get {
                return ((bool)(this["DebugTimestamp"]));
            }
            set {
                this["DebugTimestamp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugES {
            get {
                return ((bool)(this["DebugES"]));
            }
            set {
                this["DebugES"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugTrace608_708 {
            get {
                return ((bool)(this["DebugTrace608_708"]));
            }
            set {
                this["DebugTrace608_708"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DebugContainer {
            get {
                return ((bool)(this["DebugContainer"]));
            }
            set {
                this["DebugContainer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Encoding {
            get {
                return ((string)(this["Encoding"]));
            }
            set {
                this["Encoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Colors {
            get {
                return ((string)(this["Colors"]));
            }
            set {
                this["Colors"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool TextPositionTrim {
            get {
                return ((bool)(this["TextPositionTrim"]));
            }
            set {
                this["TextPositionTrim"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SentenceCaseYes {
            get {
                return ((bool)(this["SentenceCaseYes"]));
            }
            set {
                this["SentenceCaseYes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RollUpRealtime {
            get {
                return ((bool)(this["RollUpRealtime"]));
            }
            set {
                this["RollUpRealtime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool RollUpNoDupes {
            get {
                return ((bool)(this["RollUpNoDupes"]));
            }
            set {
                this["RollUpNoDupes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SentenceCaseWordList {
            get {
                return ((string)(this["SentenceCaseWordList"]));
            }
            set {
                this["SentenceCaseWordList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ColorReplacement {
            get {
                return ((string)(this["ColorReplacement"]));
            }
            set {
                this["ColorReplacement"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NoSync {
            get {
                return ((bool)(this["NoSync"]));
            }
            set {
                this["NoSync"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Fullbin {
            get {
                return ((bool)(this["Fullbin"]));
            }
            set {
                this["Fullbin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartCreditsText {
            get {
                return ((string)(this["StartCreditsText"]));
            }
            set {
                this["StartCreditsText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Generated by CCExtractor\r\nhttp://www.ccextractor.org")]
        public string EndCreditsText {
            get {
                return ((string)(this["EndCreditsText"]));
            }
            set {
                this["EndCreditsText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal StartsCreditNotBeforeMM {
            get {
                return ((decimal)(this["StartsCreditNotBeforeMM"]));
            }
            set {
                this["StartsCreditNotBeforeMM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal StartsCreditNotBeforeSS {
            get {
                return ((decimal)(this["StartsCreditNotBeforeSS"]));
            }
            set {
                this["StartsCreditNotBeforeSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal StartsCreditNotAfterMM {
            get {
                return ((decimal)(this["StartsCreditNotAfterMM"]));
            }
            set {
                this["StartsCreditNotAfterMM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public decimal StartsCreditNotAfterSS {
            get {
                return ((decimal)(this["StartsCreditNotAfterSS"]));
            }
            set {
                this["StartsCreditNotAfterSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal StartCreditsMaxDisplayedSS {
            get {
                return ((decimal)(this["StartCreditsMaxDisplayedSS"]));
            }
            set {
                this["StartCreditsMaxDisplayedSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal StartCreditsMinDisplayedSS {
            get {
                return ((decimal)(this["StartCreditsMinDisplayedSS"]));
            }
            set {
                this["StartCreditsMinDisplayedSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal EndCreditsMinDisplayedSS {
            get {
                return ((decimal)(this["EndCreditsMinDisplayedSS"]));
            }
            set {
                this["EndCreditsMinDisplayedSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("6")]
        public decimal EndCreditsMaxDisplayedSS {
            get {
                return ((decimal)(this["EndCreditsMaxDisplayedSS"]));
            }
            set {
                this["EndCreditsMaxDisplayedSS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WTVConversionFix {
            get {
                return ((bool)(this["WTVConversionFix"]));
            }
            set {
                this["WTVConversionFix"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ExportTypesetting {
            get {
                return ((bool)(this["ExportTypesetting"]));
            }
            set {
                this["ExportTypesetting"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Hauppage {
            get {
                return ((bool)(this["Hauppage"]));
            }
            set {
                this["Hauppage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autodash {
            get {
                return ((bool)(this["Autodash"]));
            }
            set {
                this["Autodash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int RollUpLinesLimit {
            get {
                return ((int)(this["RollUpLinesLimit"]));
            }
            set {
                this["RollUpLinesLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\Silicondust\\HDHomeRun")]
        public string HDHomeRunToolsPath {
            get {
                return ((string)(this["HDHomeRunToolsPath"]));
            }
            set {
                this["HDHomeRunToolsPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BOMinUTF {
            get {
                return ((bool)(this["BOMinUTF"]));
            }
            set {
                this["BOMinUTF"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ExportXDS {
            get {
                return ((bool)(this["ExportXDS"]));
            }
            set {
                this["ExportXDS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableLevDistance {
            get {
                return ((bool)(this["DisableLevDistance"]));
            }
            set {
                this["DisableLevDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LevDistanceMin {
            get {
                return ((string)(this["LevDistanceMin"]));
            }
            set {
                this["LevDistanceMin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LevDistanceMax {
            get {
                return ((string)(this["LevDistanceMax"]));
            }
            set {
                this["LevDistanceMax"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FixPTSJumps {
            get {
                return ((bool)(this["FixPTSJumps"]));
            }
            set {
                this["FixPTSJumps"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FontPathSpupng {
            get {
                return ((string)(this["FontPathSpupng"]));
            }
            set {
                this["FontPathSpupng"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool nospupngocr {
            get {
                return ((bool)(this["nospupngocr"]));
            }
            set {
                this["nospupngocr"] = value;
            }
        }
    }
}
